spring:
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.config.activate.on-profile}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 05267cb3-9710-4d55-859b-4bb2ec643586
      config:
        server-addr: localhost:8848
        namespace: 05267cb3-9710-4d55-859b-4bb2ec643586
        file-extension: yml
        refresh-enabled: true
        prefix: ${spring.application.name}
        group: DEFAULT_GROUP

    gateway:
      httpclient:
        response-timeout: 10s
        connect-timeout: 10000

      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedMethods: "*"
            allowedHeaders: "*"

      routes:
        - id: tiny-example
          uri: lb://tiny-example
          predicates:
            - Path=/tiny-example/api/**
          metadata:
            response-timeout: 10s
            connect-timeout: 10000

        - id: tiny-order
          uri: lb://tiny-order
          predicates:
            - Path=/tiny-order/api/**

        - id: tiny-pay
          uri: lb://tiny-pay
          predicates:
            - Path=/tiny-pay/api/**

logging:
  file:
    path: /Users/wangzehui/logs/tiny/${spring.application.name}
