spring:
  # 配置导入
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.config.activate.on-profile}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      # 注册中心
      discovery:
        server-addr: localhost:8848
        namespace: 05267cb3-9710-4d55-859b-4bb2ec643586
      # 配置中心
      config:
        server-addr: localhost:8848
        namespace: 05267cb3-9710-4d55-859b-4bb2ec643586
        file-extension: yml
        refresh-enabled: true
        prefix: ${spring.application.name}
        group: DEFAULT_GROUP

# log路径
logging:
  file:
    path: /Users/wangzehui/logs/tiny/${spring.application.name}
