spring:
  application:
    name: @project.artifactId@
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.config.activate.on-profile}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dc464a71-0f8a-48d6-90f3-6ec7b41e4f48
      config:
        server-addr: localhost:8848
        namespace: dc464a71-0f8a-48d6-90f3-6ec7b41e4f48
        file-extension: yml
        refresh-enabled: true
        prefix: ${spring.application.name}
        group: DEFAULT_GROUP

logging:
  file:
    path: /Users/wangzehui/Documents/Logs/tiny/${spring.application.name}
